#!/bin/sh
# Backs up the OpenShift PostgreSQL database for this application
# by Skye Book <skye.book@gmail.com>
 
NOW="$(date +"%Y-%m-%d")"
FILENAME="$OPENSHIFT_DATA_DIR/dbbackup/$OPENSHIFT_APP_NAME.$NOW.backup.sql.bak"
find $OPENSHIFT_DATA_DIR/dbbackup -name $OPENSHIFT_APP_NAME.*backup* -type f -mtime +30 -exec rm '{}' \;
pg_dump $OPENSHIFT_APP_NAME -Fc -f $FILENAME

exit 0
